### ISSUE TITLE
Error Compilation

### ISSUE THREAD

**Issue by csv610** [dnbaker/sketch#6]
Hello ,

I get the following error while compiling the codes:

rc/mhtest.cpp: In function ‘int main(int, char**)’:
src/mhtest.cpp:101:9: error: ‘aes’ has not been declared
         aes::AesCtr<uint64_t> gen1(13), gen2(1337);

I tried including #include "aesctr.h" in the code, but it produces a large number of errors.

Can someone help?

**Comment by dnbaker** [comment]
My guess is that you didn't clone this repository recursively, otherwise `aesctr/aesctr.h` would be present. You can fix this by running `git submodule update --init --recursive .` from the sketch folder or by removing and re-cloning recursively, e.g., `cd .. && rm -rf sketch && git clone --recursive https://github.com/dnbaker/sketch`.

**Comment by dnbaker** [comment]
My guess is still that this is the same error as [this other issue](https://github.com/dnbaker/dashing/issues/30), so I'll close it for now, but if your problem is different, feel free to reopen it.
